FROM minecraft-base

ENV DEBIAN_FRONTEND noninteractive
RUN cd /minecraft && \
  wget -q https://s3.amazonaws.com/Minecraft.Download/versions/1.8.7/minecraft_server.1.8.7.jar
ADD ./run-vanilla.bash /minecraft/run-vanilla.bash

WORKDIR /minecraft
EXPOSE 25565
ENTRYPOINT ["./run-vanilla.bash"]
CMD ["-Xms1G", "-Xmx2G"]
