FROM minecraft-base

RUN cd /minecraft && \
  wget -q http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1448-1.7.10/forge-1.7.10-10.13.4.1448-1.7.10-installer.jar && \
  java -jar ./forge-1.7.10-10.13.4.1448-1.7.10-installer.jar --installServer
ADD ./run-forge.bash /minecraft/run-forge.bash

WORKDIR /minecraft/data
EXPOSE 25565
ENTRYPOINT ["/minecraft/run-forge.bash"]
CMD ["-Xms1G", "-Xmx2G"]
